In [123]:
!pip install lxml html5lib beautifulsoup4

Requirement already satisfied: lxml in c:\users\jrand\miniconda3\envs\py3.8\lib\site-packages (4.9.1)
Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
     -------------------------------------- 112.2/112.2 kB 6.4 MB/s eta 0:00:00
Requirement already satisfied: beautifulsoup4 in c:\users\jrand\miniconda3\envs\py3.8\lib\site-packages (4.11.1)
Requirement already satisfied: six>=1.9 in c:\users\jrand\miniconda3\envs\py3.8\lib\site-packages (from html5lib) (1.16.0)
Requirement already satisfied: webencodings in c:\users\jrand\miniconda3\envs\py3.8\lib\site-packages (from html5lib) (0.5.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\jrand\miniconda3\envs\py3.8\lib\site-packages (from beautifulsoup4) (2.3.2.post1)
Installing collected packages: html5lib
Successfully installed html5lib-1.1

In [132]:
import pandas as pd
import sklearn 
import nltk
import numpy as np 
import matplotlib.pyplot as ply
import scipy
import re
import lxml.html
import requests

In [171]:
#functions to clean the data
def de_hashtag(row):
    temp = row['text'].split()
    res = [string for string in temp if string[0]=='#']
    return res
def websites(row):
    regex = '((http|https)\:\/\/)?[a-zA-Z0-9\.\/\?\:@\-_=#]+\.([a-zA-Z]){2,6}([a-zA-Z0-9\.\&\/\?\:@\-_=#])*'
    r = re.compile(regex)
    temp = row['text'].split()
    res = list(filter(r.match,temp))
    return res
def phone_numbers(row):
    regex = '^(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}$'
    r = re.compile(regex)
    temp = row['text'].split()
    res = list(filter(r.match,temp))
    if len(res)>0:
        return str(res[0])
    return np.nan
def get_geo(row):
    if not row['phone_number'].isna():

'def get_geo(row):\n    if len(row[])'

In [265]:
#load area codes
cols = ['area_code','city','state','country_code','lat','lng']
area_codes = pd.read_csv('https://raw.githubusercontent.com/ravisorg/Area-Code-Geolocation-Database/master/us-area-code-cities.csv',header=None,names=cols)
area_codes.area_code= area_codes.area_code.astype(int)

#inital laod of data
df = pd.read_csv('data/seventhrun.csv',header=0)
df = df.loc[:,['text','date']]
# add hastags to extra row
df['hashtags']= df.apply(de_hashtag,axis=1)
#get unique websites
df['websites']= df.apply(websites,axis=1)
# phone numbers
df['phone_numbers']= df.apply(phone_numbers,axis=1)
# add unique count to each set of tweets
df['unique_count']=df.groupby('text')['date'].rank(method='first')
df['area_code'] = df.phone_numbers.str[:3]
df['area_code'].fillna('999999999',inplace=True)
df.area_code = df.area_code.astype(int)
df= df.merge(area_codes[['area_code','state','country_code']],left_on='area_code',right_on='area_code',how='left')
df.area_code = df.area_code.astype(object)
df.replace({'area_code':999999999},{'area_code':np.nan},regex=True,inplace=True)
df.head()

,text,date,hashtags,websites,phone_numbers,unique_count,area_code,state,country_code
0,"To a GREAT Friend &amp; Kind Heart, here are A...",2020-12-07 15:57:29+00:00,"[#WakeUpCall, #FloydLittle, #Little, #Syracuse...","[https://t.co/Ho2RA8efJ2, https://t.co/1RrhcB4...",NaN,1.0,NaN,NaN,NaN
1,remember when #Syracuse was a football blue bl...,2020-10-20 22:46:37+00:00,"[#Syracuse, #brown, #mcnabb, #graves, #morris,...",[https://t.co/qzZS0jwaG4],NaN,1.0,NaN,NaN,NaN
2,#Syracuse #orange #autograph #floyd #little #j...,2020-04-18 08:39:16+00:00,"[#Syracuse, #orange, #autograph, #floyd, #litt...",[https://t.co/40pmQZGC8j],NaN,1.0,NaN,NaN,NaN
3,RT @FloppZilla: Legends! #GOAT #SYRACUSE #Cson...,2019-04-14 14:28:29+00:00,"[#GOAT, #SYRACUSE, #Csonka, #Little, #Coughlin...",[https://t.co/OBohpJXpdM],NaN,22.0,NaN,NaN,NaN
4,RT @FloppZilla: Legends! #GOAT #SYRACUSE #Cson...,2019-04-14 05:15:17+00:00,"[#GOAT, #SYRACUSE, #Csonka, #Little, #Coughlin...",[https://t.co/OBohpJXpdM],NaN,15.0,NaN,NaN,NaN

In [111]:
regex = '((http|https)\:\/\/)?[a-zA-Z0-9\.\/\?\:@\-_=#]+\.([a-zA-Z]){2,6}([a-zA-Z0-9\.\&\/\?\:@\-_=#])*'
r = re.compile(regex)

l = df.text.loc[8].split()
re.findall(r,df.text.loc[8])
res = list(filter(r.match,l))
res

['https://t.co/8KT13m8neo', 'https://t.co/iVrBEnIwO1']

In [106]:
df[df['text']==df['text'].loc[3]].sort_values('unique_count')

,text,date,hashtags,unique_count
6,RT @FloppZilla: Legends! #GOAT #SYRACUSE #Cson...,2019-04-14 01:38:29+00:00,"[#GOAT, #SYRACUSE, #Csonka, #Little, #Coughlin...",1.0
2035,RT @FloppZilla: Legends! #GOAT #SYRACUSE #Cson...,2019-04-14 01:38:29+00:00,"[#GOAT, #SYRACUSE, #Csonka, #Little, #Coughlin...",2.0
3552,RT @FloppZilla: Legends! #GOAT #SYRACUSE #Cson...,2019-04-14 01:38:29+00:00,"[#GOAT, #SYRACUSE, #Csonka, #Little, #Coughlin...",3.0
4855,RT @FloppZilla: Legends! #GOAT #SYRACUSE #Cson...,2019-04-14 01:38:29+00:00,"[#GOAT, #SYRACUSE, #Csonka, #Little, #Coughlin...",4.0
6372,RT @FloppZilla: Legends! #GOAT #SYRACUSE #Cson...,2019-04-14 01:38:29+00:00,"[#GOAT, #SYRACUSE, #Csonka, #Little, #Coughlin...",5.0
7675,RT @FloppZilla: Legends! #GOAT #SYRACUSE #Cson...,2019-04-14 01:38:29+00:00,"[#GOAT, #SYRACUSE, #Csonka, #Little, #Coughlin...",6.0
10688,RT @FloppZilla: Legends! #GOAT #SYRACUSE #Cson...,2019-04-14 01:38:29+00:00,"[#GOAT, #SYRACUSE, #Csonka, #Little, #Coughlin...",7.0
5,RT @FloppZilla: Legends! #GOAT #SYRACUSE #Cson...,2019-04-14 01:46:01+00:00,"[#GOAT, #SYRACUSE, #Csonka, #Little, #Coughlin...",8.0
2034,RT @FloppZilla: Legends! #GOAT #SYRACUSE #Cson...,2019-04-14 01:46:01+00:00,"[#GOAT, #SYRACUSE, #Csonka, #Little, #Coughlin...",9.0
3551,RT @FloppZilla: Legends! #GOAT #SYRACUSE #Cson...,2019-04-14 01:46:01+00:00,"[#GOAT, #SYRACUSE, #Csonka, #Little, #Coughlin...",10.0
4854,RT @FloppZilla: Legends! #GOAT #SYRACUSE #Cson...,2019-04-14 01:46:01+00:00,"[#GOAT, #SYRACUSE, #Csonka, #Little, #Coughlin...",11.0
6371,RT @FloppZilla: Legends! #GOAT #SYRACUSE #Cson...,2019-04-14 01:46:01+00:00,"[#GOAT, #SYRACUSE, #Csonka, #Little, #Coughlin...",12.0
7674,RT @FloppZilla: Legends! #GOAT #SYRACUSE #Cson...,2019-04-14 01:46:01+00:00,"[#GOAT, #SYRACUSE, #Csonka, #Little, #Coughlin...",13.0
10687,RT @FloppZilla: Legends! #GOAT #SYRACUSE #Cson...,2019-04-14 01:46:01+00:00,"[#GOAT, #SYRACUSE, #Csonka, #Little, #Coughlin...",14.0
4,RT @FloppZilla: Legends! #GOAT #SYRACUSE #Cson...,2019-04-14 05:15:17+00:00,"[#GOAT, #SYRACUSE, #Csonka, #Little, #Coughlin...",15.0
2033,RT @FloppZilla: Legends! #GOAT #SYRACUSE #Cson...,2019-04-14 05:15:17+00:00,"[#GOAT, #SYRACUSE, #Csonka, #Little, #Coughlin...",16.0
3550,RT @FloppZilla: Legends! #GOAT #SYRACUSE #Cson...,2019-04-14 05:15:17+00:00,"[#GOAT, #SYRACUSE, #Csonka, #Little, #Coughlin...",17.0
4853,RT @FloppZilla: Legends! #GOAT #SYRACUSE #Cson...,2019-04-14 05:15:17+00:00,"[#GOAT, #SYRACUSE, #Csonka, #Little, #Coughlin...",18.0
6370,RT @FloppZilla: Legends! #GOAT #SYRACUSE #Cson...,2019-04-14 05:15:17+00:00,"[#GOAT, #SYRACUSE, #Csonka, #Little, #Coughlin...",19.0
7673,RT @FloppZilla: Legends! #GOAT #SYRACUSE #Cson...,2019-04-14 05:15:17+00:00,"[#GOAT, #SYRACUSE, #Csonka, #Little, #Coughlin...",20.0
10686,RT @FloppZilla: Legends! #GOAT #SYRACUSE #Cson...,2019-04-14 05:15:17+00:00,"[#GOAT, #SYRACUSE, #Csonka, #Little, #Coughlin...",21.0
3,RT @FloppZilla: Legends! #GOAT #SYRACUSE #Cson...,2019-04-14 14:28:29+00:00,"[#GOAT, #SYRACUSE, #Csonka, #Little, #Coughlin...",22.0
2032,RT @FloppZilla: Legends! #GOAT #SYRACUSE #Cson...,2019-04-14 14:28:29+00:00,"[#GOAT, #SYRACUSE, #Csonka, #Little, #Coughlin...",23.0
3549,RT @FloppZilla: Legends! #GOAT #SYRACUSE #Cson...,2019-04-14 14:28:29+00:00,"[#GOAT, #SYRACUSE, #Csonka, #Little, #Coughlin...",24.0
4852,RT @FloppZilla: Legends! #GOAT #SYRACUSE #Cson...,2019-04-14 14:28:29+00:00,"[#GOAT, #SYRACUSE, #Csonka, #Little, #Coughlin...",25.0
6369,RT @FloppZilla: Legends! #GOAT #SYRACUSE #Cson...,2019-04-14 14:28:29+00:00,"[#GOAT, #SYRACUSE, #Csonka, #Little, #Coughlin...",26.0
7672,RT @FloppZilla: Legends! #GOAT #SYRACUSE #Cson...,2019-04-14 14:28:29+00:00,"[#GOAT, #SYRACUSE, #Csonka, #Little, #Coughlin...",27.0
10685,RT @FloppZilla: Legends! #GOAT #SYRACUSE #Cson...,2019-04-14 14:28:29+00:00,"[#GOAT, #SYRACUSE, #Csonka, #Little, #Coughlin...",28.0